import { authTranslations } from './en/auth';
import { homeTranslations } from './en/home';
import { dashboardTranslations } from './en/dashboard';
import { hotelTranslations } from './en/hotel';
import { paymentTranslations } from './en/payment';
import { searchTranslations } from './en/search';
import { navTranslations } from './en/nav';
import { commonTranslations } from './en/common';
import { compareTranslations } from './en/compare';
import { editBookingPageTranslations } from './edit-booking-page';
import { countriesEN } from '../countries-dict';

/**
 * @fileOverview Unified English Dictionary - Cleaned from Horizon branding
 */
export const customerEnglish = {
  common: commonTranslations,
  auth: authTranslations,
  home: homeTranslations,
  dashboard: dashboardTranslations,
  profile: {
    title: "Bermuda Profile",
    guest_type: "Elite Royal Guest",
    logout_btn: "Logout",
    edit_btn: "Edit Profile",
    save_btn: "Save Changes",
    cancel_btn: "Cancel",
    update_success: "Profile updated successfully.",
    points_title: "Royal Rewards",
    points_balance: "Current Points Balance",
    points_level: "Membership Tier",
    points_gold: "Gold Tier",
    logout_confirm_title: "Confirm Logout",
    logout_confirm_msg: "Are you sure you want to sign out?",
    logout_yes: "Yes, Sign Out",
    logout_no: "Stay"
  },
  unit_number: "Unit Number",
  notification: {
    booking_updated: "Booking details updated successfully.",
    booking_cancelled: "Booking cancelled successfully",
    payment_online_success: "Online payment confirmed successfully."
  },
  hotel: {
    ...hotelTranslations,
    ...homeTranslations.hotel,
    description_val: "A royal luxury stay that ensures your privacy and absolute luxury in the heart of Egypt."
  },
  payment: {
    ...paymentTranslations,
    pay_arrival: "Pay on Arrival",
    pay_online: "Secure Online Payment"
  },
  footer: {
    description: "Bermuda Hospitality is the symbol of luxury and privacy in Egypt.",
    about_btn: "About Bermuda",
    about_title: "Important Links",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    jobs: "Careers",
    contact_title: "Contact Us",
    location_val: "Cairo, El Gouna, Aswan",
    follow_title: "Follow Us",
    rights: "Bermuda Royal Hospitality Group. All rights reserved 2026."
  },
  loading: {
    title: "Luxury That Suits You",
    subtitle: "Attention to every detail for your royal comfort",
    processing: "Loading Bermuda Content...",
    phrase: "Bermuda: Where you lose the desire to leave"
  },
  search: {
    ...searchTranslations,
    compare: "COMPARE"
  },
  nav: {
    ...navTranslations,
    rooms: "Room Map",
    audit_logs: "Audit Logs",
    clear_all: "Clear All",
    invoice: "Invoice",
    main_menu: "Main Menu",
    notifications: "NOTIFICATIONS",
    wishlist: "WISHLIST"
  },
  notifications: {
    empty: "No notifications at the moment"
  },
  compare: compareTranslations,
  edit_page: editBookingPageTranslations.en,
  country: countriesEN,
  invoice: {
    title: "Bermuda Invoice",
    subtitle: "Internal Operations Interface",
    certified: "Certified Tax Document",
    ref_num: "Reference No",
    date_label: "Date of Issue",
    guest_section: "Contract & Guest Data",
    unit_section: "Assigned Accommodation Unit",
    stay_info: "Stay Period",
    nights_label: "Nights",
    guests_count: "Guests",
    children_count: "Children",
    extra_beds: "Extra Beds",
    breakdown: {
      title: "Analytical Financial Statement",
      accommodation: "Accommodation Services",
      night_rate: "Nightly Rate",
      total_stay: "Total Accommodation",
      extra_services: "Extra Services",
      taxes_fees: "Taxes & Fees",
      service_fees: "Service Fee (10%)",
      vat: "VAT (14%)",
      discount: "Applied Discounts",
      deposit: "Prepaid Deposit",
      grand_total: "Final Net Due",
      payment_method: "Approved Payment Method"
    },
    footer_msg: "Generated by Bermuda Cloud • All rights reserved 2026",
    print_btn: "Print Bermuda Invoice",
    back_btn: "Back to Dashboard"
  },
  city: homeTranslations.city,
  amenity: {
    wifi: "High Speed Internet",
    pool: "Royal Pool",
    spa: "World Class Spa",
    gym: "Advanced Fitness Center",
    parking: "Secure Parking",
    landmark: "Near Landmarks",
    restaurant: "Royal Fine Dining",
    trips: "Excursions"
  },
  gallery: {
    exterior: "Royal Exterior",
    room: "Rooms & Suites",
    pool: "Pools & Facilities"
  },
  meal: {
    plan_title: "Meal Plan",
    breakfast: "Breakfast",
    half_board: "Half Board",
    full_board: "Full Board",
    none: "Room Only"
  },
  booking: {
    room_selection: "Accommodation Class Selection",
    nights_count: "Nights",
    total_price: "Final Total Value",
    summary: "Royal Booking Summary",
    dates: "Selected Stay Dates",
    room_type: "Accommodation Type",
    single: "Royal Single Room",
    double: "Luxury Double Room",
    suite: "Royal Suite",
    family: "Connected Family Suite",
    total_persons: "Total Persons",
    adults: "Adults"
  },
  checkout: {
    payment_details: "Credit Card Details",
    cardholder: "Cardholder Name",
    card_number: "Card Number",
    expiry: "Expiry Date",
    cvv: "Security Code (CVV)",
    billing_info: "Certified Billing Data",
    pay_now: "Confirm Secure Payment",
    secure_msg: "Your transaction is protected by 256-bit encryption.",
    success_title: "Bermuda Booking Confirmed Successfully",
    redirect_msg: "Redirecting to your dashboard...",
    processing: "Processing your royal request...",
    city: "City",
    address: "Detailed Address",
    nationality: "Nationality / Country",
    postal: "Postal Code"
  },
  register: {
    years_label: "Yr",
    success_tag: "Success",
    denied_tag: "Denied"
  },
  walkin: {
    logic: {
      companion_count: "Additional Companions",
      companion_details: "Companion Classification",
      adult_companion: "Adult (15yr+)",
      child_label: "Child (5-14yr)",
      adult_label: "Adult",
      infant_label: "Infant",
      person_count: "Total Persons",
      primary_registered: "Primary Guest registered automatically",
      primary_guest: "Primary Guest",
      pending_age_msg: "Please specify age first"
    },
    companion_form: {
      title: "Verified Companion Data",
      edit_btn: "Review / Edit Companions",
      popup_title: "Companion Registration",
      save_btn: "Authorize All Data",
      page_info: "Page {current} of {total}",
      name: "Full Name",
      id_type: "ID Type",
      id_number: "ID Number",
      age: "Age",
      birth_cert: "Birth Cert",
      passport: "Passport",
      national_id: "National ID",
      verified: "Admin Verified",
      guest_label: "Guest"
    }
  }
};
